.TH VIEWPDF 1 "2012-04-06" "viewpdf v0.5.0"
.SH NAME
viewpdf \- view a PDF file with spellchecking and clear annotations
.SH SYNOPSIS
.B viewpdf
.RI [ file1 ]
.RI [ file2 ]
.SH DESCRIPTION
This manual page very briefly documents the \fBviewpdf\fP command.
(Click the GUI's Help button or press F1 for more information.)
.PP
\fBViewPDF\fP is a GUI application used to view PDF files.
.br
ViewPDF views PDF files, clearly showing annotations, double-words, and
spelling mistakes.
.SH AUTHOR
viewpdf was written by Mark Summerfield <mark@qtrac.eu>.
.PP
This manual page was written by Mark Summerfield <mark@qtrac.eu>
